  server:
    port: 8080

  spring:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
      properties:
        hibernate:
          format_sql: true
    web:
      resources:
        static-locations: file:uploads/
        add-mappings: true

  logging:
    level:
      org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
      org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: DEBUG

  gemini:
    api:
      key: ${GEMINI_API_KEY}

