name: CD with Gradle

on:
  push:
    branches:
      - main    # Push or PR merge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # gradlew에 실행 권한 부여
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Transfer Build File using SCP
        uses: appleboy/scp-action@master  # .jar 파일 원격 서버로 복사
        with:
          username: ubuntu
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/itzi/build/libs/"

      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/itzi || exit 1     # 경로 변경 실패 시 즉시 종료
            docker compose up -d --build --no-deps spring
            docker image prune -f         
            